many_numbers = [2, 5, 6, 23, 1, 4, 10]
print(many_numbers)
many_numbers.append(5000)
print(many_numbers)
many_numbers.remove(23)
print(many_numbers)
many_numbers.pop(0)
print(many_numbers)
removed = many_numbers.pop(0)
print(f"removed {removed}")
many_numbers.append(4)
print(many_numbers)
print(many_numbers.count(4))
